# Generated by Django 3.2.11 on 2023-09-20 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, unique=True)),
                ('username', models.CharField(max_length=32)),
                ('pwd', models.CharField(max_length=64)),
            ],
        ),
    ]
